package react.types.dom;

import css.PointerEvents;
import css.Properties as CSSProperties;
import js.html.DOMElement;

import react.types.dom.svg.*;
import react.types.or.BoolOrAuto;
import react.types.or.StringOrFloat;
import react.types.or.YesOrNo;

// TODO: abstract in css-types
typedef Cursor = String;
typedef Display = String;
typedef Mask = String;

typedef SVGAttributes<T:DOMElement> = {
	> DOMAttributes<T>,

	// Attributes which also defined in HTMLAttributes
	@:optional var className:String;
	@:optional var color:String;
	@:optional var height:StringOrFloat;
	@:optional var id:String;
	@:optional var lang:String;
	@:optional var max:StringOrFloat;
	@:optional var media:String;
	@:optional var method:String;
	@:optional var min:StringOrFloat;
	@:optional var name:String;
	@:optional var style:CSSProperties;
	@:optional var target:String;
	@:optional var type:String;
	@:optional var width:StringOrFloat;

	// Other HTML properties supported by SVG elements in browsers
	@:optional var role:String;
	@:optional var tabIndex:Int;
	@:optional var crossOrigin:CrossOrigin;

	// SVG Specific attributes
	@:optional var accentHeight:StringOrFloat;
	@:optional var accumulate:Accumulate;
	@:optional var additive:Additive;
	@:optional var alignmentBaseline:AlignmentBaseline;
	@:optional var allowReorder:YesOrNo;
	@:optional var alphabetic:StringOrFloat;
	@:optional var amplitude:StringOrFloat;
	@:optional var arabicForm:ArabicForm;
	@:optional var ascent:StringOrFloat;
	@:optional var attributeName:String;
	@:optional var attributeType:String;
	@:optional var autoReverse:Bool;
	@:optional var azimuth:StringOrFloat;
	@:optional var baseFrequency:StringOrFloat;
	@:optional var baselineShift:StringOrFloat;
	@:optional var baseProfile:StringOrFloat;
	@:optional var bbox:StringOrFloat;
	@:optional var begin:StringOrFloat;
	@:optional var bias:StringOrFloat;
	@:optional var by:StringOrFloat;
	@:optional var calcMode:StringOrFloat;
	@:optional var capHeight:StringOrFloat;
	@:optional var clip:StringOrFloat;
	@:optional var clipPath:String;
	@:optional var clipPathUnits:StringOrFloat;
	@:optional var clipRule:ClipRule;
	@:optional var colorInterpolation:ColorInterpolation;
	@:optional var colorInterpolationFilters:ColorInterpolation;
	@:optional var colorProfile:StringOrFloat;
	@:optional var colorRendering:ColorRendering;
	@:optional var contentScriptType:StringOrFloat;
	@:optional var contentStyleType:StringOrFloat;
	@:optional var cursor:Cursor;
	@:optional var cx:StringOrFloat;
	@:optional var cy:StringOrFloat;
	@:optional var d:String;
	@:optional var decelerate:StringOrFloat;
	@:optional var descent:StringOrFloat;
	@:optional var diffuseConstant:StringOrFloat;
	@:optional var direction:StringOrFloat;
	@:optional var display:Display;
	@:optional var divisor:StringOrFloat;
	@:optional var dominantBaseline:StringOrFloat;
	@:optional var dur:StringOrFloat;
	@:optional var dx:StringOrFloat;
	@:optional var dy:StringOrFloat;
	@:optional var edgeMode:StringOrFloat;
	@:optional var elevation:StringOrFloat;
	@:optional var enableBackground:StringOrFloat;
	@:optional var end:StringOrFloat;
	@:optional var exponent:StringOrFloat;
	@:optional var externalResourcesRequired:Bool;
	@:optional var fill:String;
	@:optional var fillOpacity:StringOrFloat;
	@:optional var fillRule:FillRule;
	@:optional var filter:String;
	@:optional var filterRes:StringOrFloat;
	@:optional var filterUnits:StringOrFloat;
	@:optional var floodColor:StringOrFloat;
	@:optional var floodOpacity:StringOrFloat;
	@:optional var focusable:BoolOrAuto;
	@:optional var fontFamily:String;
	@:optional var fontSize:StringOrFloat;
	@:optional var fontSizeAdjust:StringOrFloat;
	@:optional var fontStretch:StringOrFloat;
	@:optional var fontStyle:StringOrFloat;
	@:optional var fontVariant:StringOrFloat;
	@:optional var fontWeight:StringOrFloat;
	@:optional var format:StringOrFloat;
	@:optional var from:StringOrFloat;
	@:optional var fx:StringOrFloat;
	@:optional var fy:StringOrFloat;
	@:optional var g1:StringOrFloat;
	@:optional var g2:StringOrFloat;
	@:optional var glyphName:StringOrFloat;
	@:optional var glyphOrientationHorizontal:StringOrFloat;
	@:optional var glyphOrientationVertical:StringOrFloat;
	@:optional var glyphRef:StringOrFloat;
	@:optional var gradientTransform:String;
	@:optional var gradientUnits:String;
	@:optional var hanging:StringOrFloat;
	@:optional var horizAdvX:StringOrFloat;
	@:optional var horizOriginX:StringOrFloat;
	@:optional var href:String;
	@:optional var ideographic:StringOrFloat;
	@:optional var imageRendering:StringOrFloat;
	@:optional var in2:StringOrFloat;
	// @:optional var in:String; // TODO
	@:optional var intercept:StringOrFloat;
	@:optional var k1:StringOrFloat;
	@:optional var k2:StringOrFloat;
	@:optional var k3:StringOrFloat;
	@:optional var k4:StringOrFloat;
	@:optional var k:StringOrFloat;
	@:optional var kernelMatrix:StringOrFloat;
	@:optional var kernelUnitLength:StringOrFloat;
	@:optional var kerning:StringOrFloat;
	@:optional var keyPoints:StringOrFloat;
	@:optional var keySplines:StringOrFloat;
	@:optional var keyTimes:StringOrFloat;
	@:optional var lengthAdjust:StringOrFloat;
	@:optional var letterSpacing:StringOrFloat;
	@:optional var lightingColor:StringOrFloat;
	@:optional var limitingConeAngle:StringOrFloat;
	@:optional var local:StringOrFloat;
	@:optional var markerEnd:String;
	@:optional var markerHeight:StringOrFloat;
	@:optional var markerMid:String;
	@:optional var markerStart:String;
	@:optional var markerUnits:StringOrFloat;
	@:optional var markerWidth:StringOrFloat;
	@:optional var mask:Mask;
	@:optional var maskContentUnits:StringOrFloat;
	@:optional var maskUnits:StringOrFloat;
	@:optional var mathematical:StringOrFloat;
	@:optional var mode:StringOrFloat;
	@:optional var numOctaves:StringOrFloat;
	@:optional var offset:StringOrFloat;
	@:optional var opacity:StringOrFloat;
	// @:optional var operator:StringOrFloat; // TODO
	@:optional var order:StringOrFloat;
	@:optional var orient:StringOrFloat;
	@:optional var orientation:StringOrFloat;
	@:optional var origin:StringOrFloat;
	@:optional var overflow:StringOrFloat;
	@:optional var overlinePosition:StringOrFloat;
	@:optional var overlineThickness:StringOrFloat;
	@:optional var paintOrder:StringOrFloat;
	@:optional var panose1:StringOrFloat;
	@:optional var pathLength:StringOrFloat;
	@:optional var patternContentUnits:String;
	@:optional var patternTransform:StringOrFloat;
	@:optional var patternUnits:String;
	@:optional var pointerEvents:PointerEvents;
	@:optional var points:String;
	@:optional var pointsAtX:StringOrFloat;
	@:optional var pointsAtY:StringOrFloat;
	@:optional var pointsAtZ:StringOrFloat;
	@:optional var preserveAlpha:Bool;
	@:optional var preserveAspectRatio:String;
	@:optional var primitiveUnits:StringOrFloat;
	@:optional var r:StringOrFloat;
	@:optional var radius:StringOrFloat;
	@:optional var refX:StringOrFloat;
	@:optional var refY:StringOrFloat;
	@:optional var renderingIntent:StringOrFloat;
	@:optional var repeatCount:StringOrFloat;
	@:optional var repeatDur:StringOrFloat;
	@:optional var requiredExtensions:StringOrFloat;
	@:optional var requiredFeatures:StringOrFloat;
	@:optional var restart:StringOrFloat;
	@:optional var result:String;
	@:optional var rotate:StringOrFloat;
	@:optional var rx:StringOrFloat;
	@:optional var ry:StringOrFloat;
	@:optional var scale:StringOrFloat;
	@:optional var seed:StringOrFloat;
	@:optional var shapeRendering:ShapeRendering;
	@:optional var slope:StringOrFloat;
	@:optional var spacing:StringOrFloat;
	@:optional var specularConstant:StringOrFloat;
	@:optional var specularExponent:StringOrFloat;
	@:optional var speed:StringOrFloat;
	@:optional var spreadMethod:String;
	@:optional var startOffset:StringOrFloat;
	@:optional var stdDeviation:StringOrFloat;
	@:optional var stemh:StringOrFloat;
	@:optional var stemv:StringOrFloat;
	@:optional var stitchTiles:StringOrFloat;
	@:optional var stopColor:String;
	@:optional var stopOpacity:StringOrFloat;
	@:optional var strikethroughPosition:StringOrFloat;
	@:optional var strikethroughThickness:StringOrFloat;
	@:optional var string:StringOrFloat;
	@:optional var stroke:String;
	@:optional var strokeDasharray:StringOrFloat;
	@:optional var strokeDashoffset:StringOrFloat;
	@:optional var strokeLinecap:StrokeLinecap;
	@:optional var strokeLinejoin:StrokeLinejoin;
	@:optional var strokeMiterlimit:StringOrFloat;
	@:optional var strokeOpacity:StringOrFloat;
	@:optional var strokeWidth:StringOrFloat;
	@:optional var surfaceScale:StringOrFloat;
	@:optional var systemLanguage:StringOrFloat;
	@:optional var tableValues:StringOrFloat;
	@:optional var targetX:StringOrFloat;
	@:optional var targetY:StringOrFloat;
	@:optional var textAnchor:String;
	@:optional var textDecoration:StringOrFloat;
	@:optional var textLength:StringOrFloat;
	@:optional var textRendering:StringOrFloat;
	// @:optional var to:StringOrFloat; // TODO
	@:optional var transform:String;
	@:optional var u1:StringOrFloat;
	@:optional var u2:StringOrFloat;
	@:optional var underlinePosition:StringOrFloat;
	@:optional var underlineThickness:StringOrFloat;
	@:optional var unicode:StringOrFloat;
	@:optional var unicodeBidi:StringOrFloat;
	@:optional var unicodeRange:StringOrFloat;
	@:optional var unitsPerEm:StringOrFloat;
	@:optional var vAlphabetic:StringOrFloat;
	@:optional var values:String;
	@:optional var vectorEffect:VectorEffect;
	@:optional var version:String;
	@:optional var vertAdvY:StringOrFloat;
	@:optional var vertOriginX:StringOrFloat;
	@:optional var vertOriginY:StringOrFloat;
	@:optional var vHanging:StringOrFloat;
	@:optional var vIdeographic:StringOrFloat;
	@:optional var viewBox:String;
	@:optional var viewTarget:StringOrFloat;
	@:optional var visibility:Visibility;
	@:optional var vMathematical:StringOrFloat;
	@:optional var widths:StringOrFloat;
	@:optional var wordSpacing:StringOrFloat;
	@:optional var writingMode:StringOrFloat;
	@:optional var x1:StringOrFloat;
	@:optional var x2:StringOrFloat;
	@:optional var x:StringOrFloat;
	@:optional var xChannelSelector:String;
	@:optional var xHeight:StringOrFloat;
	@:optional var xlinkActuate:String;
	@:optional var xlinkArcrole:String;
	@:optional var xlinkHref:String;
	@:optional var xlinkRole:String;
	@:optional var xlinkShow:String;
	@:optional var xlinkTitle:String;
	@:optional var xlinkType:String;
	@:optional var xmlBase:String;
	@:optional var xmlLang:String;
	@:optional var xmlns:String;
	@:optional var xmlnsXlink:String;
	@:optional var xmlSpace:String;
	@:optional var y1:StringOrFloat;
	@:optional var y2:StringOrFloat;
	@:optional var y:StringOrFloat;
	@:optional var yChannelSelector:String;
	@:optional var z:StringOrFloat;
	@:optional var zoomAndPan:String;
}
